package chat

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// scheduledHandler is the runner-free /scheduled slash. It parses the
// args as "<trigger> -> <command>" and writes a YAML scaffold under
// .hero/automations/<slug>.yaml the user can review before enabling.
//
// Friendly error path: if the parser can't split on "->" or either
// side is empty, emit a chat.error with an example and exit cleanly.
func scheduledHandler(ctx context.Context, req DispatchRequest, out chan<- Event) error {
	args := ""
	if req.Slash != nil {
		args = req.Slash.Args
	}
	if args == "" {
		args = strings.TrimSpace(strings.TrimPrefix(req.Prompt, "/scheduled"))
	}
	args = strings.TrimSpace(args)

	trigger, command, ok := strings.Cut(args, "->")
	trigger = strings.TrimSpace(trigger)
	command = strings.TrimSpace(command)
	if !ok || trigger == "" || command == "" {
		example := `Example: /scheduled every weekday at 9am -> /pulse`
		out <- ErrorEvent("slash_failed", "/scheduled needs `<trigger> -> <command>`. "+example, "")
		out <- DoneEvent(0, nil)
		return nil
	}

	heroDir, err := resolveHeroDir(req.Context.Workspace)
	if err != nil {
		out <- ErrorEvent("slash_failed", err.Error(), "")
		out <- DoneEvent(0, nil)
		return nil
	}

	automationsDir := filepath.Join(heroDir, "automations")
	if err := os.MkdirAll(automationsDir, 0o755); err != nil {
		out <- ErrorEvent("slash_failed", fmt.Sprintf("create automations dir: %v", err), "")
		out <- DoneEvent(0, nil)
		return nil
	}

	slug := slugify(command)
	if slug == "" {
		slug = fmt.Sprintf("automation-%d", time.Now().Unix())
	}
	path := filepath.Join(automationsDir, slug+".yaml")
	if _, err := os.Stat(path); err == nil {
		slug = fmt.Sprintf("%s-%d", slug, time.Now().Unix())
		path = filepath.Join(automationsDir, slug+".yaml")
	}

	yaml := fmt.Sprintf(`# Generated by /scheduled on %s
# Review and adjust before enabling.
trigger:
  description: %q
action:
  command: %q
miss_policy: queue
status: draft
`, time.Now().UTC().Format(time.RFC3339), trigger, command)

	if err := os.WriteFile(path, []byte(yaml), 0o644); err != nil {
		out <- ErrorEvent("slash_failed", fmt.Sprintf("write automation: %v", err), "")
		out <- DoneEvent(0, nil)
		return nil
	}

	select {
	case <-ctx.Done():
		return ctx.Err()
	case out <- TokenEvent(fmt.Sprintf("Drafted automation at %s. Status is `draft` — review before enabling.", path)):
	}
	outcome := map[string]interface{}{"file": path, "slug": slug}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case out <- DoneEvent(0, outcome):
	}
	return nil
}
