package peering

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	contractpeering "github.com/hero-engine/hero/contracts/peering"
	"github.com/hero-engine/hero/internal/config"

	"gopkg.in/yaml.v3"
)

// writePeerManifestWithContracts puts a peer-manifest.yaml under the
// given workspace's .hero/, listing one Go-symbol contract entry.
// Returns the manifest path.
func writePeerManifestWithContracts(t *testing.T, root, peerID, pkg, name, conv string) string {
	t.Helper()
	heroDir := filepath.Join(root, ".hero")
	if err := os.MkdirAll(heroDir, 0o755); err != nil {
		t.Fatalf("mkdir hero: %v", err)
	}
	m := contractpeering.PeerManifest{
		Schema:           1,
		ContractsVersion: contractpeering.PeeringContractsVersion,
		Repo: contractpeering.RepoIdentity{
			PeerID: peerID,
			Name:   filepath.Base(root),
		},
		GeneratedAt: time.Now().UTC(),
		Contracts: &contractpeering.ContractsSection{
			Package: pkg,
			Version: 1,
			Shapes: []contractpeering.ContractEntry{
				{
					Kind:       "event-envelope",
					GoSymbol:   pkg + "." + name,
					Convention: conv,
				},
			},
		},
	}
	data, err := yaml.Marshal(m)
	if err != nil {
		t.Fatalf("marshal manifest: %v", err)
	}
	manifestPath := filepath.Join(heroDir, "peer-manifest.yaml")
	if err := os.WriteFile(manifestPath, data, 0o644); err != nil {
		t.Fatalf("write manifest: %v", err)
	}
	return manifestPath
}

// scannerFixture returns (originRoot, peerRoot) with origin
// registered against the peer and peer publishing a contract symbol.
func scannerFixture(t *testing.T) (originRoot, peerRoot, pkg, sym string) {
	t.Helper()
	root := t.TempDir()
	originRoot = filepath.Join(root, "client")
	peerRoot = filepath.Join(root, "app")
	setupWorkspace(t, originRoot, "11111111-1111-4111-8111-111111111111")
	setupWorkspace(t, peerRoot, "22222222-2222-4222-8222-222222222222")

	pkg = "contracts/events"
	sym = "Envelope"
	writePeerManifestWithContracts(t, peerRoot, "22222222-2222-4222-8222-222222222222", pkg, sym, "error-envelope")

	cfg, _ := config.Load(originRoot)
	cfg.Repos = map[string]string{"app": peerRoot}
	if err := cfg.Save(originRoot); err != nil {
		t.Fatalf("save cfg: %v", err)
	}
	return originRoot, peerRoot, pkg, sym
}

// TestScanContractImportsHit verifies a positive match: changed Go
// file in origin imports a contract symbol declared in a peer's
// manifest.
func TestScanContractImportsHit(t *testing.T) {
	originRoot, _, _, _ := scannerFixture(t)

	consumer := filepath.Join(originRoot, "api", "orders.go")
	if err := os.MkdirAll(filepath.Dir(consumer), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	src := `package api

import (
	"fmt"
	"github.com/example/app/contracts/events"
)

func Render(e events.Envelope) string {
	return fmt.Sprintf("%v", e)
}
`
	if err := os.WriteFile(consumer, []byte(src), 0o644); err != nil {
		t.Fatalf("write consumer: %v", err)
	}

	hits, err := ScanContractImports(originRoot, ScanOptions{
		ChangedFiles: []string{"api/orders.go"},
	})
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(hits) != 1 {
		t.Fatalf("expected 1 hit, got %d", len(hits))
	}
	h := hits[0]
	if h.PeerAlias != "app" {
		t.Errorf("alias: %q", h.PeerAlias)
	}
	if h.SymbolName != "Envelope" {
		t.Errorf("symbol: %q", h.SymbolName)
	}
	if h.SymbolPackage != "contracts/events" {
		t.Errorf("package: %q", h.SymbolPackage)
	}
	if h.Convention != "error-envelope" {
		t.Errorf("convention: %q", h.Convention)
	}
}

// TestScanContractImportsSkipsTestFiles verifies the spec's
// non-contract filter: *_test.go matches don't produce a signal.
func TestScanContractImportsSkipsTestFiles(t *testing.T) {
	originRoot, _, _, _ := scannerFixture(t)

	consumer := filepath.Join(originRoot, "api", "orders_test.go")
	if err := os.MkdirAll(filepath.Dir(consumer), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	src := `package api

import "github.com/example/app/contracts/events"

func TestX(t *testing.T) { var _ = events.Envelope{} }
`
	if err := os.WriteFile(consumer, []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	hits, err := ScanContractImports(originRoot, ScanOptions{
		ChangedFiles: []string{"api/orders_test.go"},
	})
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(hits) != 0 {
		t.Errorf("expected 0 hits for _test.go file, got %d", len(hits))
	}
}

// TestScanContractImportsSkipsGenerated verifies that the canonical
// Go generated-code header suppresses the signal.
func TestScanContractImportsSkipsGenerated(t *testing.T) {
	originRoot, _, _, _ := scannerFixture(t)

	consumer := filepath.Join(originRoot, "api", "gen.go")
	if err := os.MkdirAll(filepath.Dir(consumer), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	src := `// Code generated by stringer. DO NOT EDIT.

package api

import "github.com/example/app/contracts/events"

var _ = events.Envelope{}
`
	if err := os.WriteFile(consumer, []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	hits, err := ScanContractImports(originRoot, ScanOptions{
		ChangedFiles: []string{"api/gen.go"},
	})
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(hits) != 0 {
		t.Errorf("expected 0 hits for generated file, got %d", len(hits))
	}
}

// TestScanContractImportsSkipsVendor verifies the vendor-tree filter.
func TestScanContractImportsSkipsVendor(t *testing.T) {
	originRoot, _, _, _ := scannerFixture(t)

	consumer := filepath.Join(originRoot, "vendor", "x", "y.go")
	if err := os.MkdirAll(filepath.Dir(consumer), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	src := `package y
import "github.com/example/app/contracts/events"
var _ = events.Envelope{}
`
	if err := os.WriteFile(consumer, []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	hits, err := ScanContractImports(originRoot, ScanOptions{
		ChangedFiles: []string{"vendor/x/y.go"},
	})
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(hits) != 0 {
		t.Errorf("expected 0 hits for vendor file, got %d", len(hits))
	}
}

// TestScanContractImportsImportButNoReference verifies that an
// import of the package without a textual reference to the symbol
// name doesn't produce a signal — keeps the heuristic honest.
func TestScanContractImportsImportButNoReference(t *testing.T) {
	originRoot, _, _, _ := scannerFixture(t)

	consumer := filepath.Join(originRoot, "api", "side_effect.go")
	if err := os.MkdirAll(filepath.Dir(consumer), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	src := `package api

import _ "github.com/example/app/contracts/events"
`
	if err := os.WriteFile(consumer, []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	hits, err := ScanContractImports(originRoot, ScanOptions{
		ChangedFiles: []string{"api/side_effect.go"},
	})
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(hits) != 0 {
		t.Errorf("expected 0 hits when symbol not referenced, got %d", len(hits))
	}
}

// TestScanContractImportsNoPeerMatch verifies clean exit when no
// peer is reachable / has contracts published.
func TestScanContractImportsNoPeerMatch(t *testing.T) {
	root := t.TempDir()
	originRoot := filepath.Join(root, "client")
	setupWorkspace(t, originRoot, "11111111-1111-4111-8111-111111111111")
	// No peers configured at all.

	consumer := filepath.Join(originRoot, "foo.go")
	src := `package main
import "github.com/example/app/contracts/events"
var _ = events.Envelope{}
`
	if err := os.WriteFile(consumer, []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	hits, err := ScanContractImports(originRoot, ScanOptions{
		ChangedFiles: []string{"foo.go"},
	})
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(hits) != 0 {
		t.Errorf("expected 0 hits with no peer manifest, got %d", len(hits))
	}
}

// TestRenderContractImportSignal verifies the one-line output shape.
func TestRenderContractImportSignal(t *testing.T) {
	hits := []ContractImportHit{
		{
			File:              "api/orders.go",
			SymbolPackage:     "contracts/events",
			SymbolName:        "Envelope",
			FullSymbol:        "contracts/events.Envelope",
			PeerAlias:         "app",
			PeerID:            "9c1c2f3e-4a8b-4f9d-9a0e-7e1f0d8c3a55",
			Convention:        "error-envelope",
			LastChangedCommit: "4427cec",
		},
	}
	out := RenderContractImportSignal(hits)
	if out == "" {
		t.Fatal("expected non-empty signal")
	}
	checks := []string{
		"peer-contract-imports",
		"contracts/events.Envelope",
		"api/orders.go",
		"peer `app`",
		"9c1c2f3e",
		"error-envelope",
		"4427cec",
	}
	for _, s := range checks {
		if !strings.Contains(out, s) {
			t.Errorf("rendered signal missing %q:\n%s", s, out)
		}
	}
}

// TestRenderContractImportSignalEmpty: empty hits → empty signal.
func TestRenderContractImportSignalEmpty(t *testing.T) {
	if RenderContractImportSignal(nil) != "" {
		t.Error("empty hits should produce empty signal")
	}
}
