package cli

import (
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"

	"github.com/hero-engine/hero/internal/config"
	"github.com/spf13/cobra"
)

var mockCmd = &cobra.Command{
	Use:   "mock",
	Short: "List, open, or serve design mockups",
	Long: `Manages design mockups stored in .hero/mocks/.

Mockups are self-contained HTML files (or compiled native screenshots)
generated by the /mock agent command. Use this CLI command to list
existing mocks, open them in a browser, or serve them over HTTP for
sharing with teammates.

The 'detect' subcommand is the source of truth for renderer choice —
/mock invokes it and uses the JSON output verbatim, removing the
LLM judgment call from renderer selection (see 'hero spec mock
detect --help').

Generate mockups using the /mock slash command in your AI agent.`,
	RunE: runMock,
}

var (
	mockList  bool
	mockOpen  string
	mockServe bool
)

func init() {
	mockCmd.Flags().BoolVar(&mockList, "list", false, "list all available mockups")
	mockCmd.Flags().StringVar(&mockOpen, "open", "", "open a mockup by slug in the default browser")
	mockCmd.Flags().BoolVar(&mockServe, "serve", false, "serve mockups directory over HTTP for sharing")
}

func runMock(cmd *cobra.Command, args []string) error {
	if mockServe {
		return runMockServe()
	}
	if mockOpen != "" {
		return runMockOpen(mockOpen)
	}
	// Default to --list
	return runMockList()
}

type mockEntry struct {
	slug     string
	path     string
	modTime  time.Time
	isNative bool
}

func discoverMocks(mocksDir string) ([]mockEntry, error) {
	entries, err := os.ReadDir(mocksDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var mocks []mockEntry
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		indexPath := filepath.Join(mocksDir, e.Name(), "index.html")
		info, err := os.Stat(indexPath)
		if err != nil {
			continue // no index.html, skip
		}
		// Detect native mocks by the presence of screenshot.png
		screenshotPath := filepath.Join(mocksDir, e.Name(), "screenshot.png")
		_, hasScreenshot := os.Stat(screenshotPath)
		mocks = append(mocks, mockEntry{
			slug:     e.Name(),
			path:     indexPath,
			modTime:  info.ModTime(),
			isNative: hasScreenshot == nil,
		})
	}

	sort.Slice(mocks, func(i, j int) bool {
		return mocks[i].modTime.After(mocks[j].modTime)
	})

	return mocks, nil
}

func runMockList() error {
	projectRoot := findProjectRoot()
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	mocksDir := cfg.MocksDir(projectRoot)
	mocks, err := discoverMocks(mocksDir)
	if err != nil {
		return fmt.Errorf("reading mocks directory: %w", err)
	}

	if len(mocks) == 0 {
		fmt.Println("No mockups found.")
		fmt.Println("Generate mockups using the /mock command in your AI agent.")
		return nil
	}

	fmt.Println("Mockups")
	fmt.Println(strings.Repeat("─", 60))
	for _, m := range mocks {
		age := formatMockAge(m.modTime)
		tag := "[html]"
		if m.isNative {
			tag = "[native]"
		}
		fmt.Printf("  %-30s  %-8s  %s  %s\n", m.slug, tag, age, m.path)
	}
	fmt.Printf("\n%d mockup(s)\n", len(mocks))
	return nil
}

func runMockOpen(slug string) error {
	projectRoot := findProjectRoot()
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	mocksDir := cfg.MocksDir(projectRoot)
	indexPath := filepath.Join(mocksDir, slug, "index.html")

	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		return fmt.Errorf("mockup %q not found — expected %s", slug, indexPath)
	}

	return openBrowser(indexPath)
}

func runMockServe() error {
	projectRoot := findProjectRoot()
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	mocksDir := cfg.MocksDir(projectRoot)
	if _, err := os.Stat(mocksDir); os.IsNotExist(err) {
		return fmt.Errorf("no mocks directory found at %s", mocksDir)
	}

	// Find a free port
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return fmt.Errorf("finding free port: %w", err)
	}
	port := listener.Addr().(*net.TCPAddr).Port
	listener.Close()

	addr := fmt.Sprintf("127.0.0.1:%d", port)
	fmt.Printf("Serving mockups from %s\n", mocksDir)
	fmt.Printf("  http://%s\n", addr)
	fmt.Println("Press Ctrl+C to stop.")

	server := &http.Server{
		Addr:    addr,
		Handler: http.FileServer(http.Dir(mocksDir)),
	}
	return server.ListenAndServe()
}

func openBrowser(path string) error {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", path)
	case "linux":
		cmd = exec.Command("xdg-open", path)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", path)
	default:
		return fmt.Errorf("unsupported platform — open %s manually", path)
	}
	return cmd.Start()
}

func formatMockAge(t time.Time) string {
	d := time.Since(t)
	switch {
	case d < time.Minute:
		return "just now"
	case d < time.Hour:
		m := int(d.Minutes())
		if m == 1 {
			return "1 min ago"
		}
		return fmt.Sprintf("%d mins ago", m)
	case d < 24*time.Hour:
		h := int(d.Hours())
		if h == 1 {
			return "1 hour ago"
		}
		return fmt.Sprintf("%d hours ago", h)
	default:
		days := int(d.Hours() / 24)
		if days == 1 {
			return "1 day ago"
		}
		return fmt.Sprintf("%d days ago", days)
	}
}
