package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/hero-engine/hero/internal/config"
	"github.com/hero-engine/hero/internal/spec"
)

var (
	queueLimit      int
	queueHorizons   []string
	queueFormat     string
	queueSubproject string
	queueWriteQuiet bool
)

// QueueFileName is the snapshot file `hero queue write` produces. It
// lives in the hero workspace and travels with commits via the
// pre-commit hook.
const QueueFileName = "QUEUE.md"

var queueCmd = &cobra.Command{
	Use:   "queue",
	Short: "Ranked list of ready-to-work specs with paste-ready kickoff prompts",
	Long: `Curated front door over the spec corpus. Returns specs that are open
and have all hard dependencies satisfied, ranked by:

  pinned → status (delivering > planning > ...) → horizon (now > next > ...) → recency

Each result is rendered with its ` + "`## Kickoff`" + ` section so the user (or
a fresh model session) can paste a session-opener and pick up the work.

Equivalent to:
  hero list --ready --sort priority --format kickoff

For full filter / sort control see ` + "`hero list --help`" + `.
`,
	RunE: runQueue,
}

func init() {
	queueCmd.Flags().IntVar(&queueLimit, "limit", 0, "cap result count (0 = unlimited)")
	queueCmd.Flags().StringSliceVar(&queueHorizons, "horizon", nil, "filter by horizon (now, next, someday, parking)")
	queueCmd.Flags().StringVar(&queueFormat, "format", "kickoff", "output format: kickoff, text, json, table")
	queueCmd.Flags().StringVar(&queueSubproject, "subproject", "", "filter by subproject scope (e.g. engines/mlx); 'all' disables. Default: active scope from cwd")

	queueWriteCmd.Flags().BoolVarP(&queueWriteQuiet, "quiet", "q", false, "suppress non-error output")
	queueCmd.AddCommand(queueWriteCmd)
}

// queueWriteCmd renders the queue to `.hero/QUEUE.md` — a pre-projected
// snapshot for harnesses without terminal access at session start
// (notably Claude Code, where the user can't open a shell mid-session
// to run `hero queue` themselves before pasting their first prompt).
//
// The DB stays the source of truth; this file is a convenience cache.
// Fully overwritten every refresh — never hand-edited, no agent half,
// merge driver regenerates on conflict.
var queueWriteCmd = &cobra.Command{
	Use:   "write",
	Short: "Render the queue to .hero/QUEUE.md (snapshot for cold-start surfaces)",
	Long: `Writes the current ranked queue to .hero/QUEUE.md, fully overwriting
prior content. Invoked by the pre-commit hook so the snapshot travels
with the commit, and by /handoff, /design, /deliver after spec
mutations.

The file is committed (not gitignored) and merge-driven by hero-next:
on conflicts, git regenerates instead of marking up.`,
	RunE: runQueueWrite,
}

func runQueueWrite(cmd *cobra.Command, args []string) error {
	projectRoot := findProjectRoot()
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	heroDir := cfg.HeroDir(projectRoot)
	if _, err := os.Stat(heroDir); os.IsNotExist(err) {
		return fmt.Errorf("no hero workspace found (run 'hero init' first)")
	}

	content, err := RenderQueueSnapshot(heroDir)
	if err != nil {
		return err
	}

	target := filepath.Join(heroDir, QueueFileName)
	if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", target, err)
	}
	if !queueWriteQuiet {
		fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", target)
	}
	return nil
}

// RenderQueueSnapshot produces the content for `.hero/QUEUE.md` from
// the spec corpus under heroDir. Exposed for the merge driver and any
// caller that needs the queue rendered without going through the CLI.
func RenderQueueSnapshot(heroDir string) (string, error) {
	specs, err := spec.Discover(heroDir)
	if err != nil {
		return "", fmt.Errorf("discover specs: %w", err)
	}

	sel := spec.Selector{
		Filter: spec.Filter{Ready: true, ExcludeClosedDefault: true},
		Sort:   spec.SortPriority,
	}
	ready := sel.Apply(specs)

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "<!--")
	fmt.Fprintln(&buf, "  Auto-generated by `hero queue write`. Do not hand-edit — overwritten on every refresh.")
	fmt.Fprintln(&buf, "  Source of truth lives in each spec's `## Kickoff` section under `.hero/specs/<slug>/spec.md`.")
	fmt.Fprintln(&buf, "  Refresh manually: `hero queue write`. Auto-refresh: pre-commit hook + /handoff /design /deliver.")
	fmt.Fprintln(&buf, "-->")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "# Hero Ready Queue")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "_Generated: %s · %d ready %s_\n",
		time.Now().UTC().Format(time.RFC3339), len(ready), pluralSpec(len(ready)))
	fmt.Fprintln(&buf)

	if len(ready) == 0 {
		fmt.Fprintln(&buf, "Queue is empty — every open spec is either blocked or has no `## Kickoff` section to surface.")
		fmt.Fprintln(&buf)
		fmt.Fprintln(&buf, "Run `hero list --blocked` to see what's waiting on dependencies, or `hero check` to find specs missing kickoff sections.")
		return buf.String(), nil
	}

	if err := renderSpecsKickoff(&buf, ready); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func pluralSpec(n int) string {
	if n == 1 {
		return "spec"
	}
	return "specs"
}

func runQueue(cmd *cobra.Command, args []string) error {
	refreshIndexBeforeRead()
	specs, err := loadAllSpecs()
	if err != nil {
		return err
	}

	horizons := make([]spec.Horizon, 0, len(queueHorizons))
	for _, h := range queueHorizons {
		horizons = append(horizons, spec.Horizon(strings.TrimSpace(h)))
	}

	subproject := resolveSubprojectFilter(queueSubproject)
	maybePrintScopeHint(cmd.ErrOrStderr(), queueSubproject, subproject)

	// Surface specs that arrived via cross-repo handoff before the
	// ranked queue. These are work this workspace owes its peers and
	// shouldn't sink under unrelated work.
	renderIncomingHandoffs(cmd.OutOrStdout(), specs)

	sel := spec.Selector{
		Filter: spec.Filter{
			Horizons:             horizons,
			Ready:                true,
			ExcludeClosedDefault: true,
			Subproject:           subproject,
		},
		Sort:  spec.SortPriority,
		Limit: queueLimit,
	}

	out := sel.Apply(specs)
	if len(out) == 0 {
		fmt.Fprintln(cmd.OutOrStdout(), "Queue is empty — every open spec is either blocked or has no `## Kickoff` section to surface.")
		return nil
	}
	return renderSpecs(cmd.OutOrStdout(), out, queueFormat)
}

// renderIncomingHandoffs lists specs that arrived from a peer via
// cross-repo handoff (received_from frontmatter set) and are still in
// an open state.
func renderIncomingHandoffs(w interface{ Write(p []byte) (int, error) }, specs []*spec.Spec) {
	var incoming []*spec.Spec
	for _, s := range specs {
		if s.ReceivedFrom == nil {
			continue
		}
		if s.Status == spec.StatusCompleted || s.Status == spec.StatusSuperseded {
			continue
		}
		incoming = append(incoming, s)
	}
	if len(incoming) == 0 {
		return
	}
	fmt.Fprintf(w, "Incoming Handoffs (%d):\n", len(incoming))
	for _, s := range incoming {
		from := s.ReceivedFrom.PeerAliasDisplay
		if from == "" {
			from = s.ReceivedFrom.PeerID
		}
		fmt.Fprintf(w, "  %-30s  %-12s  from %s/%s\n",
			s.Slug, string(s.Status), from, s.ReceivedFrom.OriginatorSlug)
		if s.ReceivedFrom.Reason != "" {
			fmt.Fprintf(w, "    reason: %s\n", s.ReceivedFrom.Reason)
		}
	}
	fmt.Fprintln(w)
}
