package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/hero-engine/hero/internal/async"
	"github.com/hero-engine/hero/internal/config"
	"github.com/hero-engine/hero/internal/install"
	"github.com/hero-engine/hero/internal/spec"
	"github.com/hero-engine/hero/internal/version"
	"github.com/hero-engine/hero/internal/workspace"
	"github.com/spf13/cobra"
)

var (
	statusAll     bool
	statusHorizon string
)

var statusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show the current state of the hero workspace",
	Long: `Displays specs in planning, delivering, completed, conventions, and decisions.

By default shows only horizon ∈ {now, next} — the actionable set.
Use --all to include someday/parking, or --horizon someday/parking
to view those specifically. Hidden specs are summarized in the
footer so you know they're there.`,
	RunE: runStatus,
}

func init() {
	statusCmd.Flags().BoolVar(&statusAll, "all", false, "include someday/parking specs in the listing")
	statusCmd.Flags().StringVar(&statusHorizon, "horizon", "", "show only specs at this horizon (now/next/someday/parking)")

	RegisterSmoke(statusCmd, func(cmd *cobra.Command) error {
		return runStatus(cmd, nil)
	})
}

func runStatus(cmd *cobra.Command, args []string) error {
	projectRoot := findProjectRoot()
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	heroDir := cfg.HeroDir(projectRoot)
	if _, err := os.Stat(heroDir); os.IsNotExist(err) {
		return fmt.Errorf("no hero workspace found (run 'hero init' first)")
	}

	// Surface workspace location and active scope when running from a
	// satellite or subfolder. Quiet when at root with no scope.
	printWorkspaceContext(projectRoot, heroDir)

	specs, err := spec.Discover(heroDir)
	if err != nil {
		return fmt.Errorf("discovering specs: %w", err)
	}

	// Apply horizon filter to work specs only. Knowledge types
	// (conventions, decisions, notes, rules, …) aren't subject to
	// horizon filtering — they're reference material.
	hiddenByHorizon := 0
	keep := func(s *spec.Spec) bool {
		if !s.IsWorkSpec() {
			return true
		}
		if statusHorizon != "" {
			ok := s.EffectiveHorizon() == spec.Horizon(statusHorizon)
			if !ok {
				hiddenByHorizon++
			}
			return ok
		}
		if statusAll {
			return true
		}
		ok := s.IsActiveHorizon()
		if !ok {
			hiddenByHorizon++
		}
		return ok
	}

	var planning, inReview, delivering, completed []*spec.Spec
	var conventions, decisions, rules, external, context, notes []*spec.Spec
	for _, s := range specs {
		switch {
		case s.Type == spec.TypeConvention:
			conventions = append(conventions, s)
		case s.Type == spec.TypeDecision:
			decisions = append(decisions, s)
		case s.Type == spec.TypeRule:
			rules = append(rules, s)
		case s.Type == spec.TypeExternal:
			external = append(external, s)
		case s.Type == spec.TypeContext:
			context = append(context, s)
		case s.Type == spec.TypeNote:
			notes = append(notes, s)
		default:
			if !keep(s) {
				continue
			}
			switch s.Status {
			case spec.StatusPlanning:
				planning = append(planning, s)
			case spec.StatusInReview:
				inReview = append(inReview, s)
			case spec.StatusDelivering:
				delivering = append(delivering, s)
			case spec.StatusCompleted:
				completed = append(completed, s)
			}
		}
	}

	// Print in-flight work
	printSpecGroup("Delivering", delivering, projectRoot, true)
	printSpecGroup("In Review", inReview, projectRoot, true)
	printSpecGroup("Planning", planning, projectRoot, true)
	fmt.Println()

	// Print completed
	if len(completed) > 0 {
		fmt.Printf("Specs (%d):\n", len(completed))
		for _, s := range completed {
			fmt.Printf("  %-30s  %-10s  %s\n", s.Slug, string(s.Type), s.Title)
		}
	} else {
		fmt.Println("Specs: (none)")
	}

	// Split Context into human-authored vs auto-generated code-scan stubs.
	// The auto entries (one per package) are useful in aggregate but
	// drown the actual context docs when listed line-by-line.
	var humanContext, autoContext []*spec.Spec
	for _, s := range context {
		if isAutoGenerated(s) {
			autoContext = append(autoContext, s)
		} else {
			humanContext = append(humanContext, s)
		}
	}

	knowledgeTypes := []struct {
		label string
		items []*spec.Spec
	}{
		{"Conventions", conventions},
		{"Decisions", decisions},
		{"Rules", rules},
		{"External", external},
		{"Context", humanContext},
		{"Notes", notes},
	}

	for _, kt := range knowledgeTypes {
		if len(kt.items) > 0 {
			fmt.Printf("\n%s (%d):\n", kt.label, len(kt.items))
			for _, s := range kt.items {
				fmt.Printf("  %-30s  %-8s  %s\n", s.Slug, string(s.Status), s.Title)
			}
		}
	}

	if len(autoContext) > 0 {
		fmt.Printf("\nAuto-generated code-scan stubs: %d (in .hero/knowledge/code/, hidden from this list)\n", len(autoContext))
	}

	// Async delivery jobs
	printAsyncJobs()

	// Connection health
	fmt.Println()
	printConnectionHealth(cfg)

	// Summary with version info
	totalInFlight := len(planning) + len(inReview) + len(delivering)
	totalKnowledge := len(conventions) + len(decisions) + len(rules) + len(external) + len(context) + len(notes)

	binaryVersion := rootCmd.Version
	if binaryVersion == "" {
		binaryVersion = "dev"
	}
	wsVersion := version.WorkspaceVersion(heroDir)

	versionStr := fmt.Sprintf("Hero %s", binaryVersion)
	if wsVersion != "unknown" && wsVersion != binaryVersion {
		cmp := version.CompareVersions(binaryVersion, wsVersion)
		if cmp > 0 {
			versionStr += fmt.Sprintf(" (workspace %s — upgrade available)", wsVersion)
		}
	}

	fmt.Printf("\n%s — %d in-flight, %d completed, %d knowledge entries\n",
		versionStr, totalInFlight, len(completed), totalKnowledge)

	if hiddenByHorizon > 0 && statusHorizon == "" && !statusAll {
		fmt.Printf("  %d spec(s) hidden by horizon — `hero status --all` or `hero status --horizon someday|parking` to view\n", hiddenByHorizon)
	}

	return nil
}

func printSpecGroup(label string, specs []*spec.Spec, projectRoot string, showAge bool) {
	if len(specs) == 0 {
		return
	}
	fmt.Printf("%s (%d):\n", label, len(specs))
	for _, s := range specs {
		age := time.Since(s.ModifiedAt).Truncate(time.Hour)
		relPath, _ := filepath.Rel(projectRoot, s.Path)
		claimStr := ""
		if s.ClaimedBy != "" {
			claimStr = fmt.Sprintf("  [%s]", s.ClaimedBy)
		}
		fmt.Printf("  %-30s  %-10s  %s  %s%s\n", s.Slug, string(s.Type), formatAge(age), relPath, claimStr)
	}
}

func formatAge(d time.Duration) string {
	hours := int(d.Hours())
	if hours < 24 {
		return fmt.Sprintf("%dh ago", hours)
	}
	days := hours / 24
	if days == 1 {
		return "1 day ago"
	}
	return fmt.Sprintf("%d days ago", days)
}

// printConnectionHealth shows tracker and wiki connection status.
func printConnectionHealth(cfg config.Config) {
	fmt.Println("Connections:")

	// Tracker
	if cfg.Tracker != nil && cfg.Tracker.Type != "" && cfg.Tracker.Type != "none" {
		token, err := cfg.Tracker.ResolveToken()
		if err != nil || token == "" {
			fmt.Printf("  tracker    %-10s  %-30s  no token (run 'hero connect %s')\n",
				cfg.Tracker.Type, cfg.Tracker.Project, cfg.Tracker.Type)
		} else {
			fmt.Printf("  tracker    %-10s  %-30s  token set\n",
				cfg.Tracker.Type, cfg.Tracker.Project)
		}
	} else {
		fmt.Println("  tracker    (none)  — run 'hero connect github|jira|linear' to set up")
	}

	// Confluence
	if cfg.Confluence != nil && cfg.Confluence.BaseURL != "" {
		token, err := cfg.Confluence.ResolveToken()
		if err != nil || token == "" {
			fmt.Printf("  confluence %-10s  %-30s  no token (run 'hero connect confluence')\n",
				"wiki", cfg.Confluence.SpaceKey)
		} else {
			fmt.Printf("  confluence %-10s  %-30s  token set\n",
				"wiki", cfg.Confluence.SpaceKey)
		}
	}
}

// printAsyncJobs shows active and recent async delivery jobs.
func printAsyncJobs() {
	store := async.DefaultStore()
	jobs, err := store.Load()
	if err != nil || len(jobs) == 0 {
		return
	}

	var active, recent []async.Job
	for _, j := range jobs {
		switch j.Status {
		case async.StatusPending, async.StatusRunning:
			active = append(active, j)
		case async.StatusCompleted, async.StatusFailed:
			if time.Since(j.CompletedAt) < 24*time.Hour {
				recent = append(recent, j)
			}
		}
	}

	if len(active) == 0 && len(recent) == 0 {
		return
	}

	fmt.Println("\nAsync Delivery:")
	for _, j := range active {
		elapsed := time.Since(j.StartedAt).Truncate(time.Second)
		fmt.Printf("  %-30s  %-10s  %s  branch:%s\n", j.Slug, string(j.Status), elapsed, j.Branch)
	}
	for _, j := range recent {
		status := string(j.Status)
		extra := ""
		if j.Status == async.StatusFailed && j.Error != "" {
			extra = fmt.Sprintf("  error:%s", j.Error)
		}
		if j.PRURL != "" {
			extra = fmt.Sprintf("  PR:%s", j.PRURL)
		}
		fmt.Printf("  %-30s  %-10s  %s%s\n", j.Slug, status, formatAge(time.Since(j.CompletedAt)), extra)
	}
}

// isAutoGenerated reports whether a spec was scaffolded by hero scan
// rather than authored by a human. Used to filter the per-package
// "Package: X" stubs out of the headline status listing.
func isAutoGenerated(s *spec.Spec) bool {
	for _, t := range s.Tags {
		if t == "auto-generated" || t == "code-scan" {
			return true
		}
	}
	return false
}

// printWorkspaceContext shows where the hero workspace is rooted and
// what scope is active for the current cwd. It is silent when cwd ==
// root and no subproject scope applies — keeps the default `hero
// status` output unchanged for the common case.
func printWorkspaceContext(projectRoot, heroDir string) {
	cwd, err := os.Getwd()
	if err != nil {
		return
	}
	ws, err := workspace.Locate(cwd)
	if err != nil {
		return
	}
	subs, _ := install.LoadSubprojects(heroDir)
	var declared []string
	if subs != nil {
		declared = subs.DeclaredPaths()
	}
	scope := ws.Scope(declared)

	if ws.CWD == ws.Root && scope == workspace.RootScope {
		return // at root, no scope, no need to print anything
	}

	if ws.IsSatellite {
		fmt.Printf("Workspace: %s (satellite at %s)\n", ws.Root, ws.SatellitePath)
	} else {
		fmt.Printf("Workspace: %s (cwd: %s)\n", ws.Root, ws.CWD)
	}
	if scope != workspace.RootScope {
		fmt.Printf("Scope:     %s\n", scope)
	}
	fmt.Println()
}
