package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/hero-engine/hero/internal/config"
	"github.com/hero-engine/hero/internal/extract"
	"github.com/hero-engine/hero/internal/index"
	"github.com/hero-engine/hero/internal/synthesize"
	"github.com/spf13/cobra"
)

var (
	synthesizeOut      string
	synthesizeModel    string
	synthesizeProvider string
	synthesizePacket   bool
	synthesizeDetect   bool
	synthesizeAuto     bool
	synthesizeSetMode  string
	synthesizeStale    bool
	synthesizeAmend    string
)

var synthesizeCmd = &cobra.Command{
	Use:   "synthesize <slug> [<slug>...]",
	Short: "Synthesize an explainer knowledge entry from a cluster of specs",
	Long: `Reads the named specs and the git activity across their delivery
window and produces an "explainer" knowledge entry — a "how this feature
works, as it exists now" document — at .hero/knowledge/explainers/<slug>/spec.md.

The CLI assembles the inputs deterministically (specs, commit window,
referenced decisions). Prose is generated by an LLM when a provider key is
set (ANTHROPIC_API_KEY); otherwise a scaffold is written with the assembled
material for an agent (via the hero_synthesize MCP tool) or a human to fill.

  hero synthesize cold-start-trust-hardening
  hero synthesize feat-a feat-b feat-c --out .hero/knowledge/explainers/my-feature/spec.md
  hero synthesize feat-a --packet     # print the synthesis packet, write nothing
  hero synthesize --detect            # list explainer-worthy clusters + their action
  hero synthesize --auto              # synthesize auto-eligible clusters per the mode
  hero synthesize --set-mode review   # persist autonomy: auto | review | off`,
	Args: cobra.ArbitraryArgs,
	RunE: runSynthesize,
}

func init() {
	synthesizeCmd.Flags().StringVar(&synthesizeOut, "out", "", "output path (default .hero/knowledge/explainers/<slug>/spec.md)")
	synthesizeCmd.Flags().StringVar(&synthesizeModel, "model", "", "override the LLM model for prose generation")
	synthesizeCmd.Flags().StringVar(&synthesizeProvider, "provider", "", "override the LLM provider (default anthropic)")
	synthesizeCmd.Flags().BoolVar(&synthesizePacket, "packet", false, "print the synthesis packet for an agent and write nothing")
	synthesizeCmd.Flags().BoolVar(&synthesizeDetect, "detect", false, "list explainer-worthy spec clusters with their action under the current mode")
	synthesizeCmd.Flags().BoolVar(&synthesizeAuto, "auto", false, "synthesize auto-eligible clusters per the autonomy mode; list the rest for review")
	synthesizeCmd.Flags().StringVar(&synthesizeSetMode, "set-mode", "", "persist synthesis autonomy to hero.json: auto | review | off")
	synthesizeCmd.Flags().BoolVar(&synthesizeStale, "stale", false, "list explainers whose cluster gained completed specs since last synthesis")
	synthesizeCmd.Flags().StringVar(&synthesizeAmend, "amend", "", "amend an explainer by slug from the specs that joined its cluster")
}

func runSynthesize(cmd *cobra.Command, args []string) error {
	projectRoot := findProjectRoot()
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	heroDir := cfg.HeroDir(projectRoot)
	if _, err := os.Stat(heroDir); os.IsNotExist(err) {
		return fmt.Errorf("no hero workspace found (run 'hero init' first)")
	}

	switch {
	case synthesizeSetMode != "":
		return runSynthesizeSetMode(cmd, cfg, projectRoot, synthesizeSetMode)
	case synthesizeStale:
		return runSynthesizeStale(cmd, heroDir)
	case synthesizeAmend != "":
		return runSynthesizeAmend(cmd, cfg, projectRoot, heroDir, synthesizeAmend)
	case synthesizeDetect:
		return runSynthesizeDetect(cmd, cfg, heroDir)
	case synthesizeAuto:
		return runSynthesizeAuto(cmd, cfg, projectRoot, heroDir)
	}

	if len(args) == 0 {
		return fmt.Errorf("provide spec slugs to synthesize, or --detect / --auto / --set-mode")
	}
	return synthesizeCluster(cmd, cfg, projectRoot, heroDir, args, synthesizeOut)
}

// explainerMode reads the configured autonomy mode (default review).
func explainerMode(cfg config.Config) synthesize.Mode {
	s := ""
	if cfg.Knowledge != nil {
		s = cfg.Knowledge.ExplainerSynthesis
	}
	return synthesize.NormalizeMode(s)
}

// synthesizeCluster assembles, generates (or scaffolds), writes, and indexes
// one explainer for the given slugs. Fails loud on any unresolved slug.
func synthesizeCluster(cmd *cobra.Command, cfg config.Config, projectRoot, heroDir string, slugs []string, outOverride string) error {
	pkt, err := synthesize.Assemble(heroDir, projectRoot, slugs)
	if err != nil {
		return err
	}
	today := time.Now().Format("2006-01-02")
	outPath := outOverride
	if outPath == "" {
		outPath = filepath.Join(cfg.ExplainersDir(projectRoot), pkt.OutSlug, "spec.md")
	}

	if synthesizePacket {
		fmt.Fprintln(cmd.OutOrStdout(), pkt.AgentPacket(outPath, today))
		return nil
	}

	client, err := buildExtractClient(synthesizeProvider, synthesizeModel)
	if err != nil {
		return err
	}
	var content string
	generated := false
	if client.HasKey() {
		sys, usr := pkt.Prompt()
		resp, rerr := client.Run(context.Background(), extract.Request{System: sys, User: usr, MaxOut: 3000})
		if rerr != nil {
			return fmt.Errorf("synthesis: %w", rerr)
		}
		content = pkt.Render(resp.Text, today)
		generated = true
	} else {
		content = pkt.Scaffold(today)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("creating explainer directory: %w", err)
	}
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing explainer: %w", err)
	}
	if _, err := index.RefreshIfStale(heroDir); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "warning: index refresh failed: %v\n", err)
	}

	if generated {
		fmt.Fprintf(cmd.OutOrStdout(), "Synthesized explainer: %s\n", outPath)
	} else {
		fmt.Fprintf(cmd.OutOrStdout(), "No provider key — wrote a scaffold with the synthesis material: %s\n", outPath)
		fmt.Fprintln(cmd.OutOrStdout(), "Complete it via the hero_synthesize MCP tool, or set ANTHROPIC_API_KEY and re-run.")
	}
	return nil
}

// runSynthesizeSetMode persists the autonomy mode to hero.json.
func runSynthesizeSetMode(cmd *cobra.Command, cfg config.Config, projectRoot, raw string) error {
	if raw != "auto" && raw != "review" && raw != "off" {
		return fmt.Errorf("invalid mode %q — use auto, review, or off", raw)
	}
	if cfg.Knowledge == nil {
		cfg.Knowledge = &config.KnowledgeConfig{AutoCapture: true}
	}
	cfg.Knowledge.ExplainerSynthesis = raw
	if err := cfg.Save(projectRoot); err != nil {
		return fmt.Errorf("saving config: %w", err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Explainer synthesis mode set to %q.\n", raw)
	return nil
}

// runSynthesizeDetect lists explainer-worthy clusters and the action each
// would take under the current autonomy mode.
func runSynthesizeDetect(cmd *cobra.Command, cfg config.Config, heroDir string) error {
	cands, err := synthesize.Detect(heroDir)
	if err != nil {
		return err
	}
	mode := explainerMode(cfg)
	w := cmd.OutOrStdout()
	if len(cands) == 0 {
		fmt.Fprintln(w, "No explainer-worthy clusters detected (need ≥2 completed, related specs not already covered by an explainer).")
		return nil
	}
	fmt.Fprintf(w, "%d candidate cluster(s) — mode: %s\n\n", len(cands), mode)
	for _, c := range cands {
		action := synthesize.Action(c.Confidence, mode)
		fmt.Fprintf(w, "● %s  [%s]  (confidence %.0f%%, %s)\n", c.OutSlug, strings.ToUpper(action), c.Confidence*100, strings.Join(c.Signals, ", "))
		fmt.Fprintf(w, "    specs: %s\n", strings.Join(c.Slugs, ", "))
		fmt.Fprintf(w, "    → hero synthesize %s\n\n", strings.Join(c.Slugs, " "))
	}
	return nil
}

// runSynthesizeAuto synthesizes the auto-eligible clusters under the current
// mode and lists the review-only ones without writing them.
func runSynthesizeAuto(cmd *cobra.Command, cfg config.Config, projectRoot, heroDir string) error {
	cands, err := synthesize.Detect(heroDir)
	if err != nil {
		return err
	}
	mode := explainerMode(cfg)
	w := cmd.OutOrStdout()
	var synthesized, review int
	for _, c := range cands {
		switch synthesize.Action(c.Confidence, mode) {
		case "auto":
			if err := synthesizeCluster(cmd, cfg, projectRoot, heroDir, c.Slugs, ""); err != nil {
				fmt.Fprintf(cmd.ErrOrStderr(), "warning: synthesizing %s failed: %v\n", c.OutSlug, err)
				continue
			}
			synthesized++
		case "review":
			review++
			fmt.Fprintf(w, "REVIEW: %s (%.0f%%) → hero synthesize %s\n", c.OutSlug, c.Confidence*100, strings.Join(c.Slugs, " "))
		}
	}
	fmt.Fprintf(w, "\nmode %s: %d synthesized, %d awaiting review.\n", mode, synthesized, review)
	return nil
}

// runSynthesizeStale lists explainers whose cluster gained completed specs
// since they were last synthesized.
func runSynthesizeStale(cmd *cobra.Command, heroDir string) error {
	reports, err := synthesize.StaleExplainers(heroDir)
	if err != nil {
		return err
	}
	w := cmd.OutOrStdout()
	if len(reports) == 0 {
		fmt.Fprintln(w, "All explainers are current.")
		return nil
	}
	fmt.Fprintf(w, "%d stale explainer(s):\n\n", len(reports))
	for _, r := range reports {
		fmt.Fprintf(w, "● %s — %d new spec(s): %s\n", r.ExplainerSlug, len(r.NewSlugs), strings.Join(r.NewSlugs, ", "))
		fmt.Fprintf(w, "    → hero synthesize --amend %s\n\n", r.ExplainerSlug)
	}
	return nil
}

// runSynthesizeAmend amends an explainer from the specs that joined its
// cluster, preserving the Developer Notes section and existing edits.
func runSynthesizeAmend(cmd *cobra.Command, cfg config.Config, projectRoot, heroDir, slug string) error {
	clusterSlugs, path, err := synthesize.AmendTargets(heroDir, slug)
	if err != nil {
		return err
	}
	existing, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading explainer: %w", err)
	}
	bodyAndNotes := synthesize.StripFrontmatter(string(existing))
	genBody, devNotes := synthesize.SplitDeveloperNotes(bodyAndNotes)

	pkt, err := synthesize.Assemble(heroDir, projectRoot, clusterSlugs)
	if err != nil {
		return err
	}
	today := time.Now().Format("2006-01-02")

	client, err := buildExtractClient(synthesizeProvider, synthesizeModel)
	if err != nil {
		return err
	}
	var content string
	amended := false
	if client.HasKey() {
		sys, usr := pkt.AmendPrompt(genBody)
		resp, rerr := client.Run(context.Background(), extract.Request{System: sys, User: usr, MaxOut: 3000})
		if rerr != nil {
			return fmt.Errorf("amendment: %w", rerr)
		}
		content = pkt.RenderAmended(resp.Text, devNotes, today)
		amended = true
	} else {
		content = pkt.AmendScaffold(genBody, devNotes, today)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing amended explainer: %w", err)
	}
	if _, err := index.RefreshIfStale(heroDir); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "warning: index refresh failed: %v\n", err)
	}
	if amended {
		fmt.Fprintf(cmd.OutOrStdout(), "Amended explainer: %s (Developer Notes preserved)\n", path)
	} else {
		fmt.Fprintf(cmd.OutOrStdout(), "No provider key — wrote an amend-scaffold with the new material: %s\n", path)
		fmt.Fprintln(cmd.OutOrStdout(), "Fold it in via the agent, or set ANTHROPIC_API_KEY and re-run.")
	}
	return nil
}
