package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/hero-engine/hero/internal/config"
	"github.com/hero-engine/hero/internal/extract"
	"github.com/hero-engine/hero/internal/index"
	"github.com/hero-engine/hero/internal/synthesize"
	"github.com/spf13/cobra"
)

var (
	synthesizeOut      string
	synthesizeModel    string
	synthesizeProvider string
	synthesizePacket   bool
)

var synthesizeCmd = &cobra.Command{
	Use:   "synthesize <slug> [<slug>...]",
	Short: "Synthesize an explainer knowledge entry from a cluster of specs",
	Long: `Reads the named specs and the git activity across their delivery
window and produces an "explainer" knowledge entry — a "how this feature
works, as it exists now" document — at .hero/knowledge/explainers/<slug>/spec.md.

The CLI assembles the inputs deterministically (specs, commit window,
referenced decisions). Prose is generated by an LLM when a provider key is
set (ANTHROPIC_API_KEY); otherwise a scaffold is written with the assembled
material for an agent (via the hero_synthesize MCP tool) or a human to fill.

  hero synthesize cold-start-trust-hardening
  hero synthesize feat-a feat-b feat-c --out .hero/knowledge/explainers/my-feature/spec.md
  hero synthesize feat-a --packet     # print the synthesis packet, write nothing`,
	Args: cobra.MinimumNArgs(1),
	RunE: runSynthesize,
}

func init() {
	synthesizeCmd.Flags().StringVar(&synthesizeOut, "out", "", "output path (default .hero/knowledge/explainers/<slug>/spec.md)")
	synthesizeCmd.Flags().StringVar(&synthesizeModel, "model", "", "override the LLM model for prose generation")
	synthesizeCmd.Flags().StringVar(&synthesizeProvider, "provider", "", "override the LLM provider (default anthropic)")
	synthesizeCmd.Flags().BoolVar(&synthesizePacket, "packet", false, "print the synthesis packet for an agent and write nothing")
}

func runSynthesize(cmd *cobra.Command, args []string) error {
	projectRoot := findProjectRoot()
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	heroDir := cfg.HeroDir(projectRoot)
	if _, err := os.Stat(heroDir); os.IsNotExist(err) {
		return fmt.Errorf("no hero workspace found (run 'hero init' first)")
	}

	// Assemble fails loud on any unresolved slug, before we write anything.
	pkt, err := synthesize.Assemble(heroDir, projectRoot, args)
	if err != nil {
		return err
	}
	today := time.Now().Format("2006-01-02")

	outPath := synthesizeOut
	if outPath == "" {
		outPath = filepath.Join(cfg.ExplainersDir(projectRoot), pkt.OutSlug, "spec.md")
	}

	// --packet: hand the assembled material to the caller (an agent) and
	// write nothing.
	if synthesizePacket {
		fmt.Fprintln(cmd.OutOrStdout(), pkt.AgentPacket(outPath, today))
		return nil
	}

	client, err := buildExtractClient(synthesizeProvider, synthesizeModel)
	if err != nil {
		return err
	}

	var content string
	generated := false
	if client.HasKey() {
		sys, usr := pkt.Prompt()
		resp, rerr := client.Run(context.Background(), extract.Request{System: sys, User: usr, MaxOut: 3000})
		if rerr != nil {
			return fmt.Errorf("synthesis: %w", rerr)
		}
		content = pkt.Render(resp.Text, today)
		generated = true
	} else {
		content = pkt.Scaffold(today)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("creating explainer directory: %w", err)
	}
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing explainer: %w", err)
	}
	if _, err := index.RefreshIfStale(heroDir); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "warning: index refresh failed: %v\n", err)
	}

	if generated {
		fmt.Fprintf(cmd.OutOrStdout(), "Synthesized explainer: %s\n", outPath)
	} else {
		fmt.Fprintf(cmd.OutOrStdout(), "No provider key — wrote a scaffold with the synthesis material: %s\n", outPath)
		fmt.Fprintln(cmd.OutOrStdout(), "Complete it via the hero_synthesize MCP tool, or set ANTHROPIC_API_KEY and re-run.")
	}
	return nil
}
