package scan

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"
)

// GeneratedEntry represents a knowledge base entry to be created.
type GeneratedEntry struct {
	Type    string // context, convention, rule
	Slug    string
	Path    string // absolute path to spec.md
	Content string // full spec content
}

// Generate creates knowledge base entries from a scan Result.
// heroDir is the absolute path to the .hero directory.
// It performs a deep enrichment pass (reading source files) to produce a richer
// project overview than static marker detection alone can provide.
func Generate(r *Result, heroDir string) []GeneratedEntry {
	var entries []GeneratedEntry
	date := time.Now().Format("2006-01-02")

	// 1. Deep enrichment pass — reads README, go.mod, package.json, source files
	e := Enrich(r.ProjectRoot, r)

	// 2. Rich project overview context entry (uses enrichment)
	overviewEntry := GenerateRichProjectOverview(r, e, heroDir, date)

	// 3. Import existing knowledge from AGENTS.md, .opencode/instructions, etc.
	var importResult *ImportResult
	if len(r.ImportSources) > 0 {
		var allSections []ImportedSection
		for _, src := range r.ImportSources {
			allSections = append(allSections, ParseImportSource(src)...)
		}
		importResult = ClassifyImportedSections(allSections)
		importResult.Sources = r.ImportSources

		// Enrich the project overview with imported tech stack + architecture info
		overviewEntry.Content = EnrichOverviewFromImport(overviewEntry.Content, importResult)
	}

	entries = append(entries, overviewEntry)

	// 4. Generate entries from imported knowledge (architecture, conventions, rules, commands, modules)
	if importResult != nil {
		imported := ImportToEntries(importResult, heroDir, date)
		entries = append(entries, imported...)
	}

	// 5. Generate multi-module context entry if applicable
	if r.MultiModule != nil && len(r.MultiModule.Subprojects) > 0 {
		entry := generateMultiModuleEntry(r.MultiModule, r.FrameworkDetails, heroDir, date)
		entries = append(entries, entry)
	}

	// 6. Convention stubs for detected linters/formatters
	entries = append(entries, generateLinterConventions(r, heroDir, date)...)

	// 7. Rule stubs for CI enforcement
	entries = append(entries, generateCIRules(r, heroDir, date)...)

	// 8. Convention for detected test frameworks
	entries = append(entries, generateTestConventions(r, heroDir, date)...)

	return entries
}


func generateLinterConventions(r *Result, heroDir, date string) []GeneratedEntry {
	var entries []GeneratedEntry

	for _, l := range r.Linters {
		slug := "use-" + slugify(l.Name)
		path := filepath.Join(heroDir, "knowledge", "conventions", slug, "spec.md")

		langScope := "*"
		if l.Language != "" {
			langScope = langGlob(l.Language)
		}

		content := fmt.Sprintf(`---
title: Use %s
type: convention
status: draft
created: %s
scope: ["%s"]
tags: [auto-generated, project-scan, linting]
---
# Use %s

Auto-generated by `+"`hero scan`"+`. Review and adjust.

## Rule

All %s code must pass **%s** checks. Configuration is in `+"`%s`"+`.

## Rationale

Consistent code style and catching common errors early via static analysis.

## Enforcement

<!-- Describe how this is enforced: pre-commit hook, CI check, editor integration, etc. -->

## Exceptions

<!-- When is it acceptable to disable or override a rule? -->
`, l.Name, date, langScope, l.Name, langOrAll(l.Language), l.Name, l.ConfigFile)

		entries = append(entries, GeneratedEntry{
			Type:    "convention",
			Slug:    slug,
			Path:    path,
			Content: content,
		})
	}

	return entries
}

func generateCIRules(r *Result, heroDir, date string) []GeneratedEntry {
	var entries []GeneratedEntry

	for _, ci := range r.CIProviders {
		slug := "ci-" + slugify(ci.Name)
		path := filepath.Join(heroDir, "knowledge", "rules", slug, "spec.md")

		content := fmt.Sprintf(`---
title: CI Must Pass (%s)
type: rule
status: active
created: %s
scope: ["*"]
tags: [auto-generated, project-scan, ci]
---
# CI Must Pass (%s)

Auto-generated by `+"`hero scan`"+`. Review and adjust.

## Constraint

All changes must pass the **%s** pipeline before merging. Configuration: `+"`%s`"+`.

## Rationale

Automated CI checks prevent regressions and enforce quality gates.

## Enforcement

Merge is blocked until CI passes. The pipeline configuration lives in `+"`%s`"+`.

## Exceptions

<!-- Under what circumstances can CI failures be bypassed? Who approves? -->
`, ci.Name, date, ci.Name, ci.Name, ci.ConfigFile, ci.ConfigFile)

		entries = append(entries, GeneratedEntry{
			Type:    "rule",
			Slug:    slug,
			Path:    path,
			Content: content,
		})
	}

	return entries
}

func generateMultiModuleEntry(mm *MultiModuleInfo, fwDetails []FrameworkDetail, heroDir, date string) GeneratedEntry {
	slug := "multi-module-structure"
	path := filepath.Join(heroDir, "knowledge", "context", slug, "spec.md")

	var sb strings.Builder

	sb.WriteString("---\n")
	sb.WriteString("title: Multi-Module Project Structure\n")
	sb.WriteString("type: context\n")
	sb.WriteString("status: active\n")
	sb.WriteString(fmt.Sprintf("created: %s\n", date))
	sb.WriteString("tags: [auto-generated, project-scan, multi-module]\n")
	sb.WriteString("---\n\n")

	sb.WriteString(fmt.Sprintf("## Build System: %s\n\n", mm.BuildSystem))
	sb.WriteString(fmt.Sprintf("Root configuration: `%s`\n\n", mm.RootConfig))

	sb.WriteString(fmt.Sprintf("## Subprojects (%d)\n\n", len(mm.Subprojects)))
	sb.WriteString("| Module | Directory | Language | Kind |\n")
	sb.WriteString("|--------|-----------|----------|------|\n")
	for _, sp := range mm.Subprojects {
		lang := sp.Language
		if lang == "" {
			lang = "-"
		}
		kind := sp.Kind
		if kind == "" {
			kind = "-"
		}
		sb.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s |\n", sp.Name, sp.Dir, lang, kind))
	}
	sb.WriteString("\n")

	// Add framework details if present
	if len(fwDetails) > 0 {
		sb.WriteString("## Framework Details\n\n")
		for _, fd := range fwDetails {
			sb.WriteString(fmt.Sprintf("### %s", fd.Name))
			if fd.Version != "" {
				sb.WriteString(fmt.Sprintf(" %s", fd.Version))
			}
			sb.WriteString("\n\n")
			if len(fd.Directories) > 0 {
				sb.WriteString("Modules using this framework:\n")
				for _, d := range fd.Directories {
					sb.WriteString(fmt.Sprintf("- `%s`\n", d))
				}
				sb.WriteString("\n")
			}
			if len(fd.Conventions) > 0 {
				sb.WriteString("Detected structure conventions: ")
				sb.WriteString(strings.Join(fd.Conventions, ", "))
				sb.WriteString("\n\n")
			}
		}
	}

	sb.WriteString("<!-- Add dependency relationships, build order, and deployment information -->\n")

	return GeneratedEntry{
		Type:    "context",
		Slug:    slug,
		Path:    path,
		Content: sb.String(),
	}
}

func generateTestConventions(r *Result, heroDir, date string) []GeneratedEntry {
	var entries []GeneratedEntry

	for _, tf := range r.TestFrames {
		slug := "testing-with-" + slugify(tf.Name)
		path := filepath.Join(heroDir, "knowledge", "conventions", slug, "spec.md")

		langScope := "*"
		if tf.Language != "" {
			langScope = langGlob(tf.Language)
		}

		content := fmt.Sprintf(`---
title: Testing With %s
type: convention
status: draft
created: %s
scope: ["%s"]
tags: [auto-generated, project-scan, testing]
---
# Testing With %s

Auto-generated by `+"`hero scan`"+`. Review and adjust.

## Rule

Use **%s** for %s tests. New features and bug fixes should include tests.

## Rationale

Consistent test tooling and regression prevention.

## Examples

<!-- Add examples of good test patterns for this project. -->

## Exceptions

<!-- When is it acceptable to skip tests? -->
`, tf.Name, date, langScope, tf.Name, tf.Name, langOrAll(tf.Language))

		entries = append(entries, GeneratedEntry{
			Type:    "convention",
			Slug:    slug,
			Path:    path,
			Content: content,
		})
	}

	return entries
}

// slugify converts a name to a kebab-case slug.
func slugify(name string) string {
	s := strings.ToLower(name)
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "(", "")
	s = strings.ReplaceAll(s, ")", "")
	s = strings.ReplaceAll(s, ".", "")
	s = strings.ReplaceAll(s, "/", "-")

	// Collapse multiple hyphens
	for strings.Contains(s, "--") {
		s = strings.ReplaceAll(s, "--", "-")
	}
	s = strings.TrimRight(s, "-")
	return s
}

// langGlob returns a file glob pattern for a language.
func langGlob(lang string) string {
	switch lang {
	case "Go":
		return "*.go"
	case "JavaScript":
		return "*.{js,jsx,mjs,cjs}"
	case "TypeScript":
		return "*.{ts,tsx,mts}"
	case "Python":
		return "*.py"
	case "Ruby":
		return "*.rb"
	case "Rust":
		return "*.rs"
	case "Java":
		return "*.java"
	case "PHP":
		return "*.php"
	default:
		return "*"
	}
}

// langOrAll returns the language name or "all" if empty.
func langOrAll(lang string) string {
	if lang == "" {
		return "all"
	}
	return lang
}
