package scan

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hero-engine/hero/internal/spec"
)

// MergeStrategy determines how to handle an existing knowledge entry.
type MergeStrategy int

const (
	// MergeCreate — entry doesn't exist yet, create it.
	MergeCreate MergeStrategy = iota
	// MergeUpdate — entry exists and is auto-generated/unmodified, safe to overwrite.
	MergeUpdate
	// MergeSkipCustomized — entry exists and has been customized by user, skip.
	MergeSkipCustomized
	// MergeForce — force overwrite regardless of customization.
	MergeForce
)

// MergeDecision holds the decision about how to handle a specific entry.
type MergeDecision struct {
	Entry    GeneratedEntry
	Strategy MergeStrategy
	Reason   string // human-readable explanation
	// Preserve carries authored provenance metadata (e.g. created, slug) read
	// from the existing entry so a regenerating scan restores them instead of
	// clobbering them with freshly-stamped values. Nil for new entries.
	Preserve map[string]string
}

// MergeResult holds the results of a merge operation.
type MergeResult struct {
	Created   int
	Updated   int
	Skipped   int
	Forced    int
	Decisions []MergeDecision
}

// PlanMerge examines existing knowledge entries and decides what to do with each
// generated entry. This enables idempotent scanning — running scan again will
// update auto-generated content but preserve user customizations.
func PlanMerge(entries []GeneratedEntry, force bool) []MergeDecision {
	var decisions []MergeDecision

	for _, entry := range entries {
		decision := decideMerge(entry, force)
		decisions = append(decisions, decision)
	}

	return decisions
}

// decideMerge determines the merge strategy for a single entry.
func decideMerge(entry GeneratedEntry, force bool) MergeDecision {
	existing, err := os.ReadFile(entry.Path)
	if err != nil {
		// File doesn't exist — create it
		return MergeDecision{
			Entry:    entry,
			Strategy: MergeCreate,
			Reason:   "new entry",
		}
	}

	existingContent := string(existing)
	// An existing file was read, so capture its authored provenance metadata to
	// carry forward on any strategy that regenerates the file (MergeUpdate /
	// MergeForce). MergeSkipCustomized never writes, so preservation is moot.
	preserve := preservedFields(existingContent)

	if force {
		return MergeDecision{
			Entry:    entry,
			Strategy: MergeForce,
			Reason:   "force overwrite",
			Preserve: preserve,
		}
	}

	// Check if the existing file is auto-generated and unmodified
	if isAutoGenerated(existingContent) && !isUserCustomized(existingContent) {
		return MergeDecision{
			Entry:    entry,
			Strategy: MergeUpdate,
			Reason:   "auto-generated, updating with fresh scan",
			Preserve: preserve,
		}
	}

	// Check if the existing file is imported and unmodified
	if isImported(existingContent) && !isUserCustomized(existingContent) {
		return MergeDecision{
			Entry:    entry,
			Strategy: MergeUpdate,
			Reason:   "imported content, re-importing",
			Preserve: preserve,
		}
	}

	// Existing file has been customized — skip
	return MergeDecision{
		Entry:    entry,
		Strategy: MergeSkipCustomized,
		Reason:   "user-customized (use --force to overwrite)",
	}
}

// preservedFields captures authored provenance metadata (created, slug) from an
// existing entry so a regenerating scan carries them forward rather than
// overwriting them with freshly-stamped values. Returns nil when neither field
// is present.
func preservedFields(content string) map[string]string {
	preserve := map[string]string{}
	for _, key := range []string{"created", "slug"} {
		if v := frontmatterValue(content, key); v != "" {
			preserve[key] = v
		}
	}
	if len(preserve) == 0 {
		return nil
	}
	return preserve
}

// frontmatterValue reads a top-level scalar value from YAML frontmatter,
// returning "" when there is no frontmatter or the key is absent.
func frontmatterValue(content, key string) string {
	lines := strings.Split(content, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return ""
	}
	for i := 1; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		if t == "---" {
			break
		}
		if strings.HasPrefix(t, key+":") {
			return strings.TrimSpace(strings.TrimPrefix(t, key+":"))
		}
	}
	return ""
}

// isAutoGenerated checks if the content was generated by hero scan.
func isAutoGenerated(content string) bool {
	return strings.Contains(content, "auto-generated") &&
		strings.Contains(content, "project-scan")
}

// isImported checks if the content was imported from existing docs.
func isImported(content string) bool {
	return strings.Contains(content, "tags: [imported")
}

// isUserCustomized detects if the user has materially customized auto-generated content.
// This is heuristic — we look for signs that the HTML comment placeholders have been
// filled in with real content, or that the tags have been modified.
func isUserCustomized(content string) bool {
	// If the tags line has been changed from auto-generated/imported, user customized
	lines := strings.Split(content, "\n")
	inFrontmatter := false
	foundTags := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "---" {
			if inFrontmatter {
				break // end of frontmatter
			}
			inFrontmatter = true
			continue
		}
		if inFrontmatter && strings.HasPrefix(trimmed, "tags:") {
			foundTags = true
			// If tags don't contain auto-generated or imported, user modified them
			if !strings.Contains(trimmed, "auto-generated") && !strings.Contains(trimmed, "imported") {
				return true
			}
		}
	}

	if !foundTags {
		// If there's no tags line at all, this isn't our auto-generated format
		return true
	}

	// Check if HTML comment placeholders still exist (user hasn't filled them in)
	// Placeholders look like: <!-- Add X here: ... -->
	// or: <!-- Describe how ... -->
	// or: <!-- Under what ... -->
	// If they've been removed or replaced, user has customized
	hasPlaceholder := strings.Contains(content, "<!-- Add") ||
		strings.Contains(content, "<!-- Describe") ||
		strings.Contains(content, "<!-- Under") ||
		strings.Contains(content, "<!-- When") ||
		strings.Contains(content, "<!-- Imported from:")

	// If the original placeholder comments are still there, not customized
	if hasPlaceholder {
		return false
	}

	// Check if content length grew significantly (user added real content)
	// This is a rough heuristic — auto-generated stubs are relatively short
	if len(content) > 2000 && !strings.Contains(content, "auto-generated") {
		return true
	}

	return false
}

// ExecuteMerge executes the merge decisions, writing files as needed.
func ExecuteMerge(decisions []MergeDecision) (*MergeResult, error) {
	result := &MergeResult{
		Decisions: decisions,
	}

	for _, d := range decisions {
		switch d.Strategy {
		case MergeCreate:
			if err := writeEntry(d.Entry, d.Preserve); err != nil {
				return result, fmt.Errorf("creating %s: %w", d.Entry.Path, err)
			}
			result.Created++

		case MergeUpdate:
			if err := writeEntry(d.Entry, d.Preserve); err != nil {
				return result, fmt.Errorf("updating %s: %w", d.Entry.Path, err)
			}
			result.Updated++

		case MergeForce:
			if err := writeEntry(d.Entry, d.Preserve); err != nil {
				return result, fmt.Errorf("force writing %s: %w", d.Entry.Path, err)
			}
			result.Forced++

		case MergeSkipCustomized:
			result.Skipped++
		}
	}

	return result, nil
}

// writeEntry writes a generated entry, stamping a stable slug and restoring any
// preserved provenance metadata before the write.
//
// Ordering matters: the slug is emitted first from the known GeneratedEntry.Slug
// (so brand-new entries gain a stable slug — Change 1), then preserved values
// are applied so an existing entry's authored created:/slug: win over the fresh
// stamp on regeneration (Change 2). preserve is nil for MergeCreate.
func writeEntry(entry GeneratedEntry, preserve map[string]string) error {
	dir := filepath.Dir(entry.Path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	content := entry.Content

	// Emit a stable slug for entries that carry one. Only inject when the content
	// already has frontmatter (all scan templates do); plain-text content is left
	// untouched rather than being wrapped in fabricated frontmatter.
	if entry.Slug != "" && strings.HasPrefix(strings.TrimSpace(content), "---") {
		content = spec.SetFrontmatterField(content, "slug", entry.Slug)
	}

	// Restore authored provenance from the existing entry, overriding the freshly
	// stamped values (created flips back to authored date; a dropped slug is
	// restored to the authored one).
	for k, v := range preserve {
		if v != "" {
			content = spec.SetFrontmatterField(content, k, v)
		}
	}

	return os.WriteFile(entry.Path, []byte(content), 0o644)
}
