package scan

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDecideMergeNewEntry(t *testing.T) {
	dir := t.TempDir()
	entry := GeneratedEntry{
		Type: "context",
		Slug: "test-entry",
		Path: filepath.Join(dir, "knowledge", "context", "test-entry", "spec.md"),
		Content: `---
title: Test
type: context
tags: [auto-generated, project-scan]
---
# Test
`,
	}

	d := decideMerge(entry, false)
	if d.Strategy != MergeCreate {
		t.Errorf("Strategy = %v, want MergeCreate", d.Strategy)
	}
}

func TestDecideMergeForce(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	os.WriteFile(path, []byte("user content"), 0o644)

	entry := GeneratedEntry{Path: path, Content: "new content"}

	d := decideMerge(entry, true)
	if d.Strategy != MergeForce {
		t.Errorf("Strategy = %v, want MergeForce", d.Strategy)
	}
}

func TestDecideMergeUpdateAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	existing := `---
title: Project Overview
type: context
status: active
created: 2026-01-01
tags: [auto-generated, project-scan]
---

## Tech Stack

| Layer | Technology |
|-------|------------|
| Language | Go |

## Current Gaps

- No tests

<!-- Add project-specific context here:
- Architecture overview and key design patterns
-->
`
	os.WriteFile(path, []byte(existing), 0o644)

	entry := GeneratedEntry{Path: path, Content: "updated content"}

	d := decideMerge(entry, false)
	if d.Strategy != MergeUpdate {
		t.Errorf("Strategy = %v, want MergeUpdate (auto-generated should be updatable)", d.Strategy)
	}
}

func TestDecideMergeSkipCustomized(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	// User has modified: removed auto-generated tag and added custom content
	existing := `---
title: Project Overview
type: context
status: active
tags: [project-scan, my-custom-tag]
---

## Tech Stack

Custom architecture notes that the user wrote by hand.
This is significantly more content than the auto-generated stub.
`
	os.WriteFile(path, []byte(existing), 0o644)

	entry := GeneratedEntry{Path: path, Content: "new scan content"}

	d := decideMerge(entry, false)
	if d.Strategy != MergeSkipCustomized {
		t.Errorf("Strategy = %v, want MergeSkipCustomized (user removed auto-generated tag)", d.Strategy)
	}
}

func TestDecideMergeUpdateImported(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	existing := `---
title: Architecture Overview
type: context
tags: [imported, architecture]
---

## Architecture

Some imported content.

<!-- Imported from: AGENTS.md -->
`
	os.WriteFile(path, []byte(existing), 0o644)

	entry := GeneratedEntry{Path: path, Content: "re-imported content"}

	d := decideMerge(entry, false)
	if d.Strategy != MergeUpdate {
		t.Errorf("Strategy = %v, want MergeUpdate (imported should be re-importable)", d.Strategy)
	}
}

func TestIsAutoGenerated(t *testing.T) {
	tests := []struct {
		content string
		want    bool
	}{
		{`tags: [auto-generated, project-scan]`, true},
		{`tags: [imported, architecture]`, false},
		{`tags: [custom]`, false},
		{`no frontmatter at all`, false},
	}
	for _, tt := range tests {
		got := isAutoGenerated(tt.content)
		if got != tt.want {
			t.Errorf("isAutoGenerated(%q) = %v, want %v", tt.content[:30], got, tt.want)
		}
	}
}

func TestIsImported(t *testing.T) {
	tests := []struct {
		content string
		want    bool
	}{
		{`tags: [imported, architecture]`, true},
		{`tags: [imported, module]`, true},
		{`tags: [auto-generated, project-scan]`, false},
	}
	for _, tt := range tests {
		got := isImported(tt.content)
		if got != tt.want {
			t.Errorf("isImported(%q) = %v, want %v", tt.content[:20], got, tt.want)
		}
	}
}

func TestIsUserCustomized(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name: "auto-generated with placeholder",
			content: `---
tags: [auto-generated, project-scan]
---
<!-- Add project-specific context here -->
`,
			want: false,
		},
		{
			name: "auto-generated tag removed",
			content: `---
tags: [custom-tag]
---
Some content
`,
			want: true,
		},
		{
			name: "no tags at all",
			content: `---
title: Something
---
User wrote this from scratch
`,
			want: true,
		},
		{
			name: "imported with source comment",
			content: `---
tags: [imported, architecture]
---
## Architecture
Details here
<!-- Imported from: AGENTS.md -->
`,
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isUserCustomized(tt.content)
			if got != tt.want {
				t.Errorf("isUserCustomized() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestPlanMerge(t *testing.T) {
	dir := t.TempDir()

	// Create one existing auto-generated entry
	existingPath := filepath.Join(dir, "existing", "spec.md")
	os.MkdirAll(filepath.Dir(existingPath), 0o755)
	os.WriteFile(existingPath, []byte(`---
tags: [auto-generated, project-scan]
---
Old content
<!-- Add details -->
`), 0o644)

	// Create one existing customized entry
	customPath := filepath.Join(dir, "custom", "spec.md")
	os.MkdirAll(filepath.Dir(customPath), 0o755)
	os.WriteFile(customPath, []byte(`---
tags: [user-modified]
---
Custom content the user wrote
`), 0o644)

	entries := []GeneratedEntry{
		{Slug: "new-entry", Path: filepath.Join(dir, "new", "spec.md"), Content: "new"},
		{Slug: "existing", Path: existingPath, Content: "updated"},
		{Slug: "custom", Path: customPath, Content: "would overwrite"},
	}

	decisions := PlanMerge(entries, false)

	if len(decisions) != 3 {
		t.Fatalf("expected 3 decisions, got %d", len(decisions))
	}

	strategies := map[string]MergeStrategy{}
	for _, d := range decisions {
		strategies[d.Entry.Slug] = d.Strategy
	}

	if strategies["new-entry"] != MergeCreate {
		t.Errorf("new-entry: got %v, want MergeCreate", strategies["new-entry"])
	}
	if strategies["existing"] != MergeUpdate {
		t.Errorf("existing: got %v, want MergeUpdate", strategies["existing"])
	}
	if strategies["custom"] != MergeSkipCustomized {
		t.Errorf("custom: got %v, want MergeSkipCustomized", strategies["custom"])
	}
}

func TestPlanMergeForce(t *testing.T) {
	dir := t.TempDir()

	customPath := filepath.Join(dir, "custom", "spec.md")
	os.MkdirAll(filepath.Dir(customPath), 0o755)
	os.WriteFile(customPath, []byte("user content"), 0o644)

	entries := []GeneratedEntry{
		{Slug: "custom", Path: customPath, Content: "forced"},
	}

	decisions := PlanMerge(entries, true)
	if decisions[0].Strategy != MergeForce {
		t.Errorf("expected MergeForce with --force, got %v", decisions[0].Strategy)
	}
}

func TestExecuteMerge(t *testing.T) {
	dir := t.TempDir()

	decisions := []MergeDecision{
		{
			Entry:    GeneratedEntry{Slug: "new", Path: filepath.Join(dir, "new", "spec.md"), Content: "new content"},
			Strategy: MergeCreate,
		},
		{
			Entry:    GeneratedEntry{Slug: "updated", Path: filepath.Join(dir, "updated", "spec.md"), Content: "updated content"},
			Strategy: MergeUpdate,
		},
		{
			Entry:    GeneratedEntry{Slug: "skipped", Path: filepath.Join(dir, "skipped", "spec.md"), Content: "skip"},
			Strategy: MergeSkipCustomized,
		},
	}

	result, err := ExecuteMerge(decisions)
	if err != nil {
		t.Fatalf("ExecuteMerge: %v", err)
	}

	if result.Created != 1 {
		t.Errorf("Created = %d, want 1", result.Created)
	}
	if result.Updated != 1 {
		t.Errorf("Updated = %d, want 1", result.Updated)
	}
	if result.Skipped != 1 {
		t.Errorf("Skipped = %d, want 1", result.Skipped)
	}

	// Verify files
	data, err := os.ReadFile(filepath.Join(dir, "new", "spec.md"))
	if err != nil {
		t.Fatalf("new entry not created: %v", err)
	}
	if string(data) != "new content" {
		t.Error("new entry content wrong")
	}

	data, err = os.ReadFile(filepath.Join(dir, "updated", "spec.md"))
	if err != nil {
		t.Fatalf("updated entry not created: %v", err)
	}
	if string(data) != "updated content" {
		t.Error("updated entry content wrong")
	}

	// Skipped entry should NOT exist
	if _, err := os.Stat(filepath.Join(dir, "skipped", "spec.md")); err == nil {
		t.Error("skipped entry should not have been written")
	}
}
