package scan

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestDecideMergeNewEntry(t *testing.T) {
	dir := t.TempDir()
	entry := GeneratedEntry{
		Type: "context",
		Slug: "test-entry",
		Path: filepath.Join(dir, "knowledge", "context", "test-entry", "spec.md"),
		Content: `---
title: Test
type: context
tags: [auto-generated, project-scan]
---
# Test
`,
	}

	d := decideMerge(entry, false)
	if d.Strategy != MergeCreate {
		t.Errorf("Strategy = %v, want MergeCreate", d.Strategy)
	}
}

func TestDecideMergeForce(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	os.WriteFile(path, []byte("user content"), 0o644)

	entry := GeneratedEntry{Path: path, Content: "new content"}

	d := decideMerge(entry, true)
	if d.Strategy != MergeForce {
		t.Errorf("Strategy = %v, want MergeForce", d.Strategy)
	}
}

func TestDecideMergeUpdateAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	existing := `---
title: Project Overview
type: context
status: active
created: 2026-01-01
tags: [auto-generated, project-scan]
---

## Tech Stack

| Layer | Technology |
|-------|------------|
| Language | Go |

## Current Gaps

- No tests

<!-- Add project-specific context here:
- Architecture overview and key design patterns
-->
`
	os.WriteFile(path, []byte(existing), 0o644)

	entry := GeneratedEntry{Path: path, Content: "updated content"}

	d := decideMerge(entry, false)
	if d.Strategy != MergeUpdate {
		t.Errorf("Strategy = %v, want MergeUpdate (auto-generated should be updatable)", d.Strategy)
	}
}

func TestDecideMergeSkipCustomized(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	// User has modified: removed auto-generated tag and added custom content
	existing := `---
title: Project Overview
type: context
status: active
tags: [project-scan, my-custom-tag]
---

## Tech Stack

Custom architecture notes that the user wrote by hand.
This is significantly more content than the auto-generated stub.
`
	os.WriteFile(path, []byte(existing), 0o644)

	entry := GeneratedEntry{Path: path, Content: "new scan content"}

	d := decideMerge(entry, false)
	if d.Strategy != MergeSkipCustomized {
		t.Errorf("Strategy = %v, want MergeSkipCustomized (user removed auto-generated tag)", d.Strategy)
	}
}

func TestDecideMergeUpdateImported(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spec.md")
	existing := `---
title: Architecture Overview
type: context
tags: [imported, architecture]
---

## Architecture

Some imported content.

<!-- Imported from: AGENTS.md -->
`
	os.WriteFile(path, []byte(existing), 0o644)

	entry := GeneratedEntry{Path: path, Content: "re-imported content"}

	d := decideMerge(entry, false)
	if d.Strategy != MergeUpdate {
		t.Errorf("Strategy = %v, want MergeUpdate (imported should be re-importable)", d.Strategy)
	}
}

func TestIsAutoGenerated(t *testing.T) {
	tests := []struct {
		content string
		want    bool
	}{
		{`tags: [auto-generated, project-scan]`, true},
		{`tags: [imported, architecture]`, false},
		{`tags: [custom]`, false},
		{`no frontmatter at all`, false},
	}
	for _, tt := range tests {
		got := isAutoGenerated(tt.content)
		if got != tt.want {
			t.Errorf("isAutoGenerated(%q) = %v, want %v", tt.content[:30], got, tt.want)
		}
	}
}

func TestIsImported(t *testing.T) {
	tests := []struct {
		content string
		want    bool
	}{
		{`tags: [imported, architecture]`, true},
		{`tags: [imported, module]`, true},
		{`tags: [auto-generated, project-scan]`, false},
	}
	for _, tt := range tests {
		got := isImported(tt.content)
		if got != tt.want {
			t.Errorf("isImported(%q) = %v, want %v", tt.content[:20], got, tt.want)
		}
	}
}

func TestIsUserCustomized(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name: "auto-generated with placeholder",
			content: `---
tags: [auto-generated, project-scan]
---
<!-- Add project-specific context here -->
`,
			want: false,
		},
		{
			name: "auto-generated tag removed",
			content: `---
tags: [custom-tag]
---
Some content
`,
			want: true,
		},
		{
			name: "no tags at all",
			content: `---
title: Something
---
User wrote this from scratch
`,
			want: true,
		},
		{
			name: "imported with source comment",
			content: `---
tags: [imported, architecture]
---
## Architecture
Details here
<!-- Imported from: AGENTS.md -->
`,
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isUserCustomized(tt.content)
			if got != tt.want {
				t.Errorf("isUserCustomized() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestPlanMerge(t *testing.T) {
	dir := t.TempDir()

	// Create one existing auto-generated entry
	existingPath := filepath.Join(dir, "existing", "spec.md")
	os.MkdirAll(filepath.Dir(existingPath), 0o755)
	os.WriteFile(existingPath, []byte(`---
tags: [auto-generated, project-scan]
---
Old content
<!-- Add details -->
`), 0o644)

	// Create one existing customized entry
	customPath := filepath.Join(dir, "custom", "spec.md")
	os.MkdirAll(filepath.Dir(customPath), 0o755)
	os.WriteFile(customPath, []byte(`---
tags: [user-modified]
---
Custom content the user wrote
`), 0o644)

	entries := []GeneratedEntry{
		{Slug: "new-entry", Path: filepath.Join(dir, "new", "spec.md"), Content: "new"},
		{Slug: "existing", Path: existingPath, Content: "updated"},
		{Slug: "custom", Path: customPath, Content: "would overwrite"},
	}

	decisions := PlanMerge(entries, false)

	if len(decisions) != 3 {
		t.Fatalf("expected 3 decisions, got %d", len(decisions))
	}

	strategies := map[string]MergeStrategy{}
	for _, d := range decisions {
		strategies[d.Entry.Slug] = d.Strategy
	}

	if strategies["new-entry"] != MergeCreate {
		t.Errorf("new-entry: got %v, want MergeCreate", strategies["new-entry"])
	}
	if strategies["existing"] != MergeUpdate {
		t.Errorf("existing: got %v, want MergeUpdate", strategies["existing"])
	}
	if strategies["custom"] != MergeSkipCustomized {
		t.Errorf("custom: got %v, want MergeSkipCustomized", strategies["custom"])
	}
}

func TestPlanMergeForce(t *testing.T) {
	dir := t.TempDir()

	customPath := filepath.Join(dir, "custom", "spec.md")
	os.MkdirAll(filepath.Dir(customPath), 0o755)
	os.WriteFile(customPath, []byte("user content"), 0o644)

	entries := []GeneratedEntry{
		{Slug: "custom", Path: customPath, Content: "forced"},
	}

	decisions := PlanMerge(entries, true)
	if decisions[0].Strategy != MergeForce {
		t.Errorf("expected MergeForce with --force, got %v", decisions[0].Strategy)
	}
}

// TestScanPreservesCreatedAndSlugOnUpdate guards the regression where re-running
// hero scan flipped an existing entry's authored created: to today and dropped
// its slug: (undoing the created-date backfill on every scan). On MergeUpdate the
// authored created:/slug: must be carried forward, and the write must be
// idempotent across repeated scans. Fresh MergeCreate entries must still get
// today's created: and an emitted slug:.
func TestScanPreservesCreatedAndSlugOnUpdate(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "knowledge", "rules", "ci-github-actions", "spec.md")
	os.MkdirAll(filepath.Dir(path), 0o755)

	// (1) Existing auto-generated, uncustomized entry with authored provenance.
	existing := `---
title: CI Must Pass (GitHub Actions)
type: rule
slug: ci-github-actions
status: active
created: 2020-01-01
scope: ["*"]
tags: [auto-generated, project-scan, ci]
---
# CI Must Pass (GitHub Actions)

Auto-generated by ` + "`hero scan`" + `. Review and adjust.

## Exceptions

<!-- Under what circumstances can CI failures be bypassed? Who approves? -->
`
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatalf("write existing: %v", err)
	}

	// (2) Freshly generated content for the same slug/path — today's created:,
	// and (per the bug) no slug: line at all.
	today := time.Now().Format("2006-01-02")
	freshContent := `---
title: CI Must Pass (GitHub Actions)
type: rule
status: active
created: ` + today + `
scope: ["*"]
tags: [auto-generated, project-scan, ci]
---
# CI Must Pass (GitHub Actions)

Auto-generated by ` + "`hero scan`" + `. Review and adjust.

## Exceptions

<!-- Under what circumstances can CI failures be bypassed? Who approves? -->
`
	entry := GeneratedEntry{
		Type:    "rule",
		Slug:    "ci-github-actions",
		Path:    path,
		Content: freshContent,
	}

	// (3) Plan → assert MergeUpdate → execute.
	decisions := PlanMerge([]GeneratedEntry{entry}, false)
	if len(decisions) != 1 || decisions[0].Strategy != MergeUpdate {
		t.Fatalf("strategy = %v, want MergeUpdate", decisions[0].Strategy)
	}
	if _, err := ExecuteMerge(decisions); err != nil {
		t.Fatalf("ExecuteMerge: %v", err)
	}

	// (4) Authored created:/slug: preserved after the first scan.
	assertField(t, path, "created", "2020-01-01")
	assertField(t, path, "slug", "ci-github-actions")

	// (5) Scan a second time — still unchanged (idempotency).
	decisions = PlanMerge([]GeneratedEntry{entry}, false)
	if decisions[0].Strategy != MergeUpdate {
		t.Fatalf("second scan strategy = %v, want MergeUpdate", decisions[0].Strategy)
	}
	if _, err := ExecuteMerge(decisions); err != nil {
		t.Fatalf("second ExecuteMerge: %v", err)
	}
	assertField(t, path, "created", "2020-01-01")
	assertField(t, path, "slug", "ci-github-actions")

	// (6) MergeCreate still stamps today's created: and emits a slug: — the
	// preservation logic must not leak into fresh creation.
	newPath := filepath.Join(dir, "knowledge", "rules", "ci-fresh", "spec.md")
	newEntry := GeneratedEntry{
		Type: "rule",
		Slug: "ci-fresh",
		Path: newPath,
		Content: `---
title: CI Fresh
type: rule
status: active
created: ` + today + `
tags: [auto-generated, project-scan, ci]
---
# CI Fresh
`,
	}
	createDecisions := PlanMerge([]GeneratedEntry{newEntry}, false)
	if createDecisions[0].Strategy != MergeCreate {
		t.Fatalf("new entry strategy = %v, want MergeCreate", createDecisions[0].Strategy)
	}
	if _, err := ExecuteMerge(createDecisions); err != nil {
		t.Fatalf("create ExecuteMerge: %v", err)
	}
	assertField(t, newPath, "created", today)
	assertField(t, newPath, "slug", "ci-fresh")
}

// assertField reads content back from disk and asserts a top-level frontmatter
// scalar equals want.
func assertField(t *testing.T, path, key, want string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read back %s: %v", path, err)
	}
	got := frontmatterValue(string(data), key)
	if got != want {
		t.Errorf("%s: %s = %q, want %q\n---\n%s", filepath.Base(filepath.Dir(path)), key, got, want, string(data))
	}
	if key == "slug" && !strings.Contains(string(data), "slug: "+want) {
		t.Errorf("%s: expected literal `slug: %s` line, content:\n%s", path, want, string(data))
	}
}

func TestExecuteMerge(t *testing.T) {
	dir := t.TempDir()

	decisions := []MergeDecision{
		{
			Entry:    GeneratedEntry{Slug: "new", Path: filepath.Join(dir, "new", "spec.md"), Content: "new content"},
			Strategy: MergeCreate,
		},
		{
			Entry:    GeneratedEntry{Slug: "updated", Path: filepath.Join(dir, "updated", "spec.md"), Content: "updated content"},
			Strategy: MergeUpdate,
		},
		{
			Entry:    GeneratedEntry{Slug: "skipped", Path: filepath.Join(dir, "skipped", "spec.md"), Content: "skip"},
			Strategy: MergeSkipCustomized,
		},
	}

	result, err := ExecuteMerge(decisions)
	if err != nil {
		t.Fatalf("ExecuteMerge: %v", err)
	}

	if result.Created != 1 {
		t.Errorf("Created = %d, want 1", result.Created)
	}
	if result.Updated != 1 {
		t.Errorf("Updated = %d, want 1", result.Updated)
	}
	if result.Skipped != 1 {
		t.Errorf("Skipped = %d, want 1", result.Skipped)
	}

	// Verify files
	data, err := os.ReadFile(filepath.Join(dir, "new", "spec.md"))
	if err != nil {
		t.Fatalf("new entry not created: %v", err)
	}
	if string(data) != "new content" {
		t.Error("new entry content wrong")
	}

	data, err = os.ReadFile(filepath.Join(dir, "updated", "spec.md"))
	if err != nil {
		t.Fatalf("updated entry not created: %v", err)
	}
	if string(data) != "updated content" {
		t.Error("updated entry content wrong")
	}

	// Skipped entry should NOT exist
	if _, err := os.Stat(filepath.Join(dir, "skipped", "spec.md")); err == nil {
		t.Error("skipped entry should not have been written")
	}
}
